frontend/src/components/footer/footerMenu/footerMenu.tsx
#11 
푸터 아이콘 페이지 연결 추가
푸터 아이콘 클릭 시 해당 페이지로 이동
=> feat : 아이콘 페이지 연결 추가

frontend/src/pages/vote/vote.tsx, frontend/src/styles/theme.ts
=> fix: 세미콜론 누락 수정

frontend/src/App.tsx, frontend/src/components/bubbleHeader/bubbleHeader.style.ts, frontend/src/components/bubbleHeader/bubbleHeader.tsx, frontend/src/components/countdown/countDown.tsx, frontend/src/components/footer/footerUserName/footerUserName.style.ts, frontend/src/components/vote/Input/input.tsx, frontend/src/hooks/useTimer.ts, frontend/src/hooks/useVote.ts, frontend/src/pages/vote/vote.tsx, frontend/src/store/useVoteStore.ts
#10 
투표 생성 여부에 다라 헤더 변경 기능 추가
투표가 생성되어 있다면 투표 모달이 열리도록, 투표가 생성되어 있지 않다면 투표 만들기 버튼으로 변경
=> feat : 투표 생성 여부에 따라 헤더 변경 기능 추가

backend/socket/userHandler.ts, frontend/src/socket/userHandler.ts
#6 
users 테이블 사용 하지 않도록 변경
기존 DB 작업 -> socket으로 이용하도록 수정
=> feat : user관련 내용은 DB를 사용하지 않도록 수정

.idea/workspace.xml, frontend/src/App.tsx, frontend/src/components/footer/footerUserName/footerUserName.tsx, frontend/src/components/modal/userNameChange/userNameChange.tsx, frontend/src/pages/Chat/chat.tsx, frontend/src/router/router.tsx, frontend/src/socket/userHandler.ts, frontend/src/store/useUserStore.ts
=> feat : 첫 렌더링 시 닉네임 모달 열기 추가

.idea/workspace.xml, docker-compose.yml, frontend/src/components/header/header.tsx, frontend/src/components/systemMessage/chatSystemMessage/chatSystemMessage.style.ts, frontend/src/hooks/useAuth.ts, frontend/src/pages/Chat/chat.tsx, frontend/src/socket/socketManager.ts, frontend/src/socket/userHandler.ts, frontend/src/store/useUserStore.ts
=> feat: 입장 시 사용자 인원 반영, 메세지 출력 기능 추가

backend/db/mariadb.ts, backend/socket/quizHandler.ts, docker-compose.yml, frontend/src/socket/userHandler.ts
AWS DB 생성 및 연결 작업 완료
기존 quiz 테스트 데이터 삭제
=> chore : AWS DB 작업 완료

backend/socket/voteHandler.ts, frontend/src/App.tsx, frontend/src/components/bubbleHeader/bubbleHeader.style.ts, frontend/src/components/bubbleHeader/bubbleHeader.tsx, frontend/src/components/footer/footerMenu/footerMenu.tsx, frontend/src/components/vote/content/content.style.ts, frontend/src/components/vote/content/content.tsx, frontend/src/hooks/useAuth.ts, frontend/src/hooks/useVote.ts, frontend/src/pages/vote/vote.tsx, frontend/src/socket/userHandler.ts, frontend/src/socket/voteHandler.ts, frontend/src/store/useRoomStore.ts, frontend/src/store/useVoteStore.ts
=> feat : 투표 생성자에 따라 투표 버튼 변화 기능 추가

backend/socket/voteHandler.ts, frontend/src/common/types.ts, frontend/src/components/bubbleHeader/bubbleHeader.tsx, frontend/src/components/header/header.tsx, frontend/src/hooks/useVote.ts, frontend/src/socket/voteHandler.ts, frontend/src/store/useVoteStore.ts
=> feat : 새로운 클라이언트 실행 시 기존 투표 불러오는 기능 추가" 

.gitignore, backend/socket/voteHandler.ts, frontend/src/components/bubbleHeader/bubbleHeader.tsx, frontend/src/components/vote/content/content.tsx, frontend/src/components/vote/result/result.tsx, frontend/src/hooks/useVote.ts, frontend/src/socket/voteHandler.ts, frontend/src/store/useVoteStore.ts
=> fix: 투표 집계 오류 수정

frontend/.env
=> chore: env 파일 추적 제외

backend/socket/socketManager.ts, backend/socket/userHandler.ts, frontend/src/pages/Chat/chat.tsx
userId가 생성된 유저만 퇴장되도록 수정
기존에는 닉네임을 생성하지 않아도 X버튼을 누를 경우 redis 인원 업데이트가 되는 오류가 있었음
=> fix : userId가 생성된 유저만 퇴장되도록 수정

backend/socket/userHandler.ts, backend/socket/voteHandler.ts, frontend/src/App.tsx, frontend/src/components/bubbleHeader/bubbleHeader.tsx, frontend/src/components/footer/footerMenu/footerMenu.tsx, frontend/src/components/layout/layout.tsx, frontend/src/components/vote/content/content.tsx, frontend/src/hooks/useVote.ts, frontend/src/pageHeader/pageHeader.style.ts, frontend/src/pageHeader/pageHeader.tsx, frontend/src/pages/vote/vote.tsx, frontend/src/router/router.tsx, frontend/src/socket/userHandler.ts, frontend/src/socket/voteHandler.ts, frontend/src/store/useRoomStore.ts, frontend/src/store/useUserStore.ts, frontend/src/store/useVoteStore.ts
=> feat: 라우터 제거, 투표 여부에 따라 모달 로직 분리

frontend/src/App.tsx, frontend/src/components/vote/result/result.tsx, frontend/src/hooks/useTimer.ts, frontend/src/hooks/useVote.ts, frontend/src/pageHeader/pageHeader.tsx, frontend/src/pages/Chat/chat.tsx, frontend/src/socket/messageHandler.ts, frontend/src/socket/userHandler.ts, frontend/src/socket/voteHandler.ts, frontend/src/store/useChatStore.ts
=> feat: 투표 결과 출력 기능 추가

frontend/src/components/systemMessage/chatSystemMessage/chatSystemMessage.tsx, frontend/src/components/systemMessage/chatUserMessage/chatUserMessage.style.ts, frontend/src/components/vote/content/content.tsx
=> design: chatSystemMessage 시간 제거, chatUserMessage 간격 수정

backend/socket/messageHandler.ts, frontend/src/components/footer/footerInput/footerInput.tsx, frontend/src/components/systemMessage/SystemMessage.tsx, frontend/src/socket/messageHandler.ts, frontend/src/socket/userHandler.ts
메세지 전달 시 두번씩 출력되거나 이전에 보낸 메세지가 출력되는 오류 수정
다른 사람이 보낸 메세지를 소켓 이벤트 발생 시 컴포넌트 에러가 발생하여 잠시 주석처리했습니다. 추후 수정 필요
=> fix : 메세지 두번씩 출력, 이전 메세지 전달되는 오류 수정

frontend/src/hooks/useTimer.ts, frontend/src/socket/userHandler.ts
=> fix : 닉네임 변경 채팅 두 번 나오는 오류 수정

frontend/src/pages/Chat/chat.tsx
=> feat : 스크롤 시점 아래로 고정 추가

frontend/src/components/footer/footerMenu/footerMenu.tsx, frontend/src/components/radioBtn/radioBtn.style.ts, frontend/src/components/radioBtn/radioBtn.tsx, frontend/src/components/vote/content/content.tsx
=> design: 라디오 버튼 텍스트 클릭 시 상태 반영

backend/common/types.ts, backend/socket/quizHandler.ts, backend/socket/userHandler.ts, frontend/src/common/types.ts, frontend/src/components/footer/footerInput/footerInput.tsx, frontend/src/components/footer/footerMenu/footerMenu.tsx, frontend/src/socket/quizHandler.ts, frontend/src/store/useQuizStore.ts
투표 또는 퀴즈가 진행중일 때 새로운 투표/퀴즈를 생성할 수 없도록 함
=> feat : 투표 또는 퀴즈가 진행중일 때 새로운 투표/퀴즈를 생성할 수 없도록 함

frontend/src/components/countdown/countDown.tsx, frontend/src/hooks/useTimer.ts, frontend/src/socket/voteHandler.ts, frontend/src/store/useTimerStore.ts
=> fix: 투표 종료 시 투표 참여자의 투표 상태 초기화하지 못하는 오류 수정

frontend/src/hooks/useAuth.ts, frontend/src/hooks/useVote.ts, frontend/src/socket/userHandler.ts
=> chore: 주석 일부 제거

frontend/src/pages/ChatRoom.tsx, frontend/src/pages/components/MessageList.tsx
[#59] 2팀 투표 & 퀴즈
시간 표기 수정
일반 메시지 수신 시 시간 표기 버그 수정
=> feat: 시간 표기 수정

frontend/src/components/layout/layout.tsx, frontend/src/components/systemMessage/chatUserMessage/chatUserMessage.tsx, frontend/src/pageHeader/pageHeader.tsx
=> fix: 퀴즈 헤더 안보이는 오류 해결

frontend/src/components/layout/layout.tsx, frontend/src/components/systemMessage/SystemMessage.style.ts, frontend/src/components/systemMessage/chatUserMessage/chatUserMessage.style.ts, frontend/src/pageHeader/pageHeader.tsx
=> design : 말풍선 간격 조정

backend/socket/messageHandler.ts, docker-compose.yml, frontend/src/socket/messageHandler.ts, frontend/src/store/useUserStore.ts
퀴즈 종료 시 유저 메세지 시간이 다르게 생성되어 시스템 메세지가 정답 메세지보다 위로 올라가는 현상 수정
=> fix : 퀴즈 종료 시 유저 메세지 시간이 다르게 생성되어 시스템 메세지가 정답 메세지보다 위로 올라가는 현상 수정

frontend/src/components/vote/content/content.tsx, frontend/src/components/vote/voteCard.tsx
투표 모달 연 상태로 퀴즈를 시작한 뒤 투표를 생성하면 퀴즈와 투표 동시진행되는 오류 수정
=> fix : 투표 모달 연 상태로 퀴즈를 시작한 뒤 투표를 생성하면 퀴즈와 투표 동시진행되는 오류 수정

backend/app.ts, backend/socket/messageHandler.ts, backend/socket/quizHandler.ts, backend/socket/socketManager.ts, backend/socket/userHandler.ts, backend/socket/voteHandler.ts, frontend/src/components/footer/footerMenu/footerMenu.tsx, frontend/src/components/systemMessage/SystemMessage.tsx, frontend/src/components/vote/content/content.tsx, frontend/src/hooks/useTimer.ts, frontend/src/hooks/useVote.ts, frontend/src/socket/messageHandler.ts, frontend/src/socket/quizHandler.ts, frontend/src/socket/socketManager.ts, frontend/src/socket/userHandler.ts, frontend/src/socket/voteHandler.ts, frontend/src/store/useVoteStore.ts
backend, frontend 폴더 내 불필요한 주석, console 삭제
=> refactor : 불필요한 주석, console 삭제
